### ISSUE TITLE
[DB] 각 페이지에 대한 동적인 데이터 정리

### ISSUE THREAD

**Issue by KIMSEI1124** [MultiProject23/React-Project#54]
# 개요

각 페이지에 대한 동적으로 필요한 데이터를 정리합니다.

## 할일

- [x] Cart
- [x] Details
- [x] Join
- [x] Login
- [x] Main - Header
- [x] My
- [ ] Outfit
- [x] Product
- [x] Review

## ETC

정리한 내용은 아래에다가 적어주시면 감사합니다.
포멧은 `데이터 명 : 간단한 설명` 으로 하겠습니다.
예를 들면 아래와 같습니다.

```
페이지 이름
id : 제품의 고유 번호
image : 제품의 이미지
name : 제품의 이름
...
```

**Comment by KIMSEI1124** [comment]
# Main
```
count : 장바구니에 담긴 물건의 개수
```

**Comment by KIMSEI1124** [comment]
# My

## 나의 정보
```
name: 유저의 이름
email: 유저의 이메일
phoneNumber: 유저의 전화번호
```

## 주소정보
```
name: 수취인의 이름
zipCode: 우편번호
address: 상세주소
```

## 주문정보
```
id: 주문번호
date: 주문일
productName: 제품 이름
productOption: 제품 옵션
productPrice: 제품 가격
orderStatus: 주문 상태
```

**Comment by rrimm** [comment]
> # Details
> ## 상품 상세페이지
> ```
> product_id: 제품 코드(고유 번호)
> product_name: 제품의 이름
> product_price: 제품의 가격
> product_image: 제품의 이미지
> product_info: 제품에 대한 설명
> product_stock: 제품 재고
> count: 제품 판매량
> ```
> 
> ## 연관상품
> ```
> product_name: 제품의 이름
> product_price: 제품의 가격
> product_image: 제품의 이미지
> ```
>

**Comment by KIMSEI1124** [comment]
@rrimm 

캐러셀에 대한 데이터가 부족해보입니다.
또한 연관 상품에 해당 제품으로 이동하기 위한 정보가 필요합니다. 제품의 고유 번호가 부족해보이네요 추가해주시면 감사하겠습니다.

**Comment by rrimm** [comment]
1. 캐러셀 데이터 예시 추가하였습니다.
2. 연관상품으로 이동하기 위한 product_id를 추가하였습니다.

**Comment by syw2858** [comment]
### **Login**
```
email: 유저 이메일
pw: 비밀번호

```

JSON
```
{
   "email":"admin0314@gmail.com",
   "pw":"qwerty0310"
}

```

### **Join**

```
email: 유저 이메일
pw: 비밀번호
name: 이름
birth: 생년월일
phone: 전화번호
```

JSON

```
{
   "email":"admin0314@gmail.com",
   "pw":"qwerty0310",
   "name":"홍길동",
   "birth":"990401",
   "phone":"010-3333-2222"
}
```

**Comment by paul3148** [comment]
Cart
product_id : 상품id
product_name : 상품명
product_count : 수량
product_option : 옵션
product_price : 판매가
product_saleprice : 할인가

JSON
{
    "cart" : [
        {
            "product_id": 1,
            "product_image":"image001.png",
            "product_name": "바이스윙 윈드브레이커-네이비",
            "product_count": 1,
            "product_option" : "M",
            "product_price" : 299000,
            "product_saleprice" : 290000
        },

        {
            "product_id": 2,
            "product_image":"image002.png",
            "product_name": "발마칸 코트",
            "product_count": 3,
            "product_option" : "L",
            "product_price" : 231000,
            "product_saleprice" : 200000
        },

        {
            "product_id": 2,
            "product_image":"image002.png",
            "product_name": "발마칸 코트",
            "product_count": 3,
            "product_option" : "L",
            "product_price" : 231000,
            "product_saleprice" : 200000
        },

        {
            "product_id": 2,
            "product_image":"image002.png",
            "product_name": "발마칸 코트",
            "product_count": 3,
            "product_option" : "L",
            "product_price" : 231000,
            "product_saleprice" : 200000
        },

        {
            "product_id": 3,
            "product_image":"image003.png",
            "product_name": "클래식 블랙",
            "product_count": 2,
            "product_option" : "270",
            "product_price" : 85500,
            "product_saleprice" : 80000
        },

        {
            "product_id": 4,
            "product_image":"image004.png",
            "product_name": "바이스윙 윈드브레이커-베이지",
            "product_count": 2,
            "product_option" : "L",
            "product_price" : 299000,
            "product_saleprice" : 290000
        },

        {
            "product_id": 5,
            "product_image":"image005.png",
            "product_name": "베이식 블레이저",
            "product_count": 1,
            "product_option" : "L",
            "product_price" : 81900,
            "product_saleprice" : 80000
        },

        {
            "product_id": 6,
            "product_image":"image006.png",
            "product_name": "YACHT JACKET",
            "product_count": 2,
            "product_option" : "L",
            "product_price" : 113000,
            "product_saleprice" : 110000
        }
    ]
}

**Comment by jYoung15628** [comment]
### Product page
### 상품 정보

> 

product_code: 상품 코드
product_name: 상품 이름
product_price: 상품 가격
product_stock: 상품 재고
product_img: 상품 이미지
product_type: 상품 종류
Recommended_products:추천 상품
### Json 파일 예시

> `{

"product_code":1001,
"product_name":"Denim pants",
"product_price":98000 ,
"product_stock":100,
"product_img":"pants1.jpg",
"product_type":"pants"
},
"Recommended_products":[
     {
        "product_id":1002,
        "product_name":"Straight pants",
        "product_price":98000,
        "product_image":"pants2.jpg"
     },
     {
        "product_id":1003,
        "product_name":"Crop pants",
        "product_price":90000,
        "product_image":"pants3.jpg"
     },
     {
        "product_id":1004,
        "product_name":"Highwaist pants",
        "product_price":98000,
        "product_image":"pants4.jpg"
     }
  ]
`

**Comment by umtaemin1125** [comment]
Review Page
---
- review_id : 리뷰 (리뷰 고유 번호)
- product_name : 상품명
- email : 유저 이메일
- review_image : 리뷰 상품 이미지
- product_type : 상품 카테고리 (hat, top, outer, bag, pants, shoes, basic)
---
JSON 파일 예시
---
<pre>
<code>
{
"reviews": [
      {
        "review_id": 1,
        "product_name": "상품명",
        "review_content": "리뷰내용1",
        "email": "작성자 이메일",
        "review_image": "/img/ReviewTest.jpg"
        "product_type" : "pants"
      },
      {
        "review_id": 2,
        "product_name": "상품명",
        "review_content": "리뷰내용2",
        "email": "작성자 이메일",
        "review_image": "/img/ReviewTest.jpg"
        "product_type" : "outer"
      },
      {
        "review_id": 3,
        "product_name": "상품명",
        "review_content": "리뷰내용3",
        "email": "작성자 이메일",
        "review_image": "/img/ReviewTest.jpg"
        "product_type" : "hat"
      },
]
}
</code>
</pre>
